--
- hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: update apt cache
      yum:
        name=* state=latest
        lock_timeout: 180

- include: control.yml
- include: database.yml
- include: webserver.yml
