---
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: verify apache service
      command: service httpd status

    - name: verify apache is listening on 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  gather_facts: false
  tasks:
    - name: verify mysql service
      command: service mysql status

    - name: verify mysql is listening on 3306
      wait_for: port=3306 timeout=1

- hosts: control
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{item}} return_content=yes
      with_items: ec2-18-233-226-144.compute-1.amazonaws.com
      register: web_index

    - fail: msg="index failed to return content"
      when: "'MySQL connection to the ip-10-21-170-115.ec2.internal RDS instance is established' not in item.content"
      with_items: "{{web_index.results}}"
